### PR TITLE
update requirements.txt and set up environment

### LINKED ISSUE #28: Update requirements and add configs for google authentication
I have gone through the project and get an issue. There are some requirements missing in requirements.txt and added credentials, that were added in the admin side to the code. updates in settings and requirements.txt

### PR DESCRIPTION
**Pull request by ritikalohia**
setting up environment  variable and make a .env file.

### CODE REVIEW

**Review by ExpressHermes — CHANGES_REQUESTED** [review]
The requirements.txt contains unnecessary dependencies. Remove them, please.  Some examples of these dependencies: numpy, opencv, flask, etc.

**Comment by ExpressHermes** [comment]
@ritikalohia Don't create separate PR to make new changes, make a commit to this PR only

**Comment by ritikalohia** [comment]
ok , I remove them and commit to the same

**Comment by ritikalohia** [comment]
I have make changes as required, you can accept the pr now

**Review by ExpressHermes — APPROVED** [review]
good work

**Pull request merged**
